CastXML/CastXML

- src/Output.cxx
Update the file format revision number so tools can distinguish
the new content from that produced by older CastXML versions.
GitHub-Issues: CastXML/CastXML#52, CastXML/CastXML#55, CastXML/CastXML#56
> Output: Update `cvs_revision` number to indicate output change

- CMakeLists.txt
Some distros package LLVM and Clang resources separately with
a layout of the form
<prefix>/lib/llvm/<major-version>/lib
<prefix>/lib/clang/<full-version>/include
Update our search for `CLANG_RESOURCE_DIR` to support this.
> Search for Clang resources in a clang/ sibling of llvm/

- src/Output.cxx
- test/expect/castxml1.any.Function-Argument-decay.xml.txt
- test/expect/gccxml.any.Function-Argument-decay.xml.txt
- test/input/Function-Argument-decay.cxx
Some types decay when used in function parameters (e.g. arrays become pointers).  When this occurs, add an `original_type` attribute to reference the original type without decay.
Also add a test case covering multi-dimensional arrays in function arguments.  Only the top-level decays.
Issue: #96
> Output: Add original types to decayed function parameters

- README.rst
- src/Utils.cxx
- src/castxml.cxx
LLVM/Clang commit r334518 (Refactor ExecuteAndWait to take StringRefs,
2018-06-12) changed the signature of `ExecuteAndWait`.  Update our call.
LLVM/Clang commit r330216 (Rename sys::Process::GetArgumentVector ->
sys::windows::GetCommandLineArguments, 2018-04-17) removed the
`GetArgumentVector` API we were using.  Instead use `InitLLVM` to get
proper command-line arguments as was done for Clang by LLVM/Clang
commit r330067 (Use InitLLVM in clang as well, 2018-04-13).
Also document existing support for LLVM/Clang 6.0.
> Port to LLVM/Clang SVN r338041 (trunk)

- share/castxml/detect_vs.c
- share/castxml/detect_vs.cpp
- test/CMakeLists.txt
- test/cc-msvc.c
- test/expect/cmd.cc-msvc-std-c++17-E.stdout.txt
Use the table at [1] to add a few missing VS 2017 predefined macros to our detection table.  Also add the `__STDCPP_DEFAULT_NEW_ALIGNMENT__` predefined VS macro.  This macro is missing from the main MSVC predefined macro list but is documented by [2] and [3].  Also add `__STDCPP_STRICT_POINTER_SAFETY__` as documented by [3] in case MSVC ever starts defining it.
[1] https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros
[2] https://docs.microsoft.com/en-us/cpp/build/reference/zc-alignednew
[3] https://en.cppreference.com/w/cpp/preprocessor/replace
Fixes: #125
> Detect: Add more VS predefined macros

- src/CMakeLists.txt
Support linking against the shared version of LLVM libraries.
> cmake: work with LLVM_LINK_LLVM_DYLIB

- src/CMakeLists.txt
Since #132 our `llvm_libs` variable is a list of LLVM components rather than a list of raw library names.  The `version.lib` library is not a LLVM component.  Fortunately we can simply drop it because LLVM now computes the proper list of libraries for its components.
Fixes: #133
> cmake: drop explicit link to version.lib on Windows

- doc/conf.py.in
The warning is:
WARNING: Support for evaluating Python 2 syntax is deprecated and will be removed in Sphinx 4.0. Convert /builddir/build/BUILD/CastXML-9c91919574d84eefabe3ea656f08568c280da89e/doc/conf.py to Python 3 syntax.
> Convert from old python syntax to fix warning from new sphinx version

- doc/manual/castxml.1.rst
- src/RunClang.cxx
- src/Utils.cxx
- src/Utils.h
- src/Version.cmake
- test/CMakeLists.txt
- test/expect/cmd.cc-gnu-c-src-c-E.stdout.txt
- test/expect/cmd.cc-gnu-c-tgt-i386-opt-E.stdout.txt
- test/expect/cmd.cc-gnu-src-cxx-E.stdout.txt
- test/expect/cmd.cc-gnu-tgt-i386-opt-E.stdout.txt
- test/expect/cmd.cc-msvc-builtin-1800-E.stdout.txt
- test/expect/cmd.cc-msvc-builtin-1900-E.stdout.txt
- test/expect/cmd.cc-msvc-c-src-c-E.stdout.txt
- test/expect/cmd.cc-msvc-src-cxx-E.stdout.txt
- test/expect/cmd.cc-msvc-std-c++17-E.stdout.txt
- test/expect/cmd.predefined-macros.stdout.txt.in
- test/input/predefined.c
- test/input/predefined.cxx
- test/input/predefined.h
Use the format `<major>.<minor>.<patch>[-rc<n>][-<id>]` for release
versions and `<major>.<minor>.<date>[-<id>]` for development versions.
Assume we will identify exact release versions with a `v<ver>` tag
on a commit with subject `CastXML <ver>`.  Aadd an `-<id>` suffix to
versions that are not exact release commits.
> Version: Update version scheme to distinguish release and dev versions

- doc/conf.py.in
Set the Sphinx `html_theme_options` to give the generated documentation
a brighter and softer look than the default colors.
> doc: use brighter colors for html theme

- src/Detect.cxx
- test/cc-gnu.c
When using `--castxml-cc-gnu` we replace the compiler's builtin include directory with our copy of Clang's builtins.  We had been relying on the presence of `emmintrin.h` to detect the GNU builtin directory, but it does not exist on ppc64.  Check for `altivec.h` too to fix this.
Also filter out GNU predefined macros that conflict with Clang's builtins on ppc64.
> Detect: Fix builtins and includes with GNU compiler on ppc64

- CMakeLists.txt
Related to CastXML/CastXML#148.
CastXML uses `find_package(Clang)` which in case there is more than one LLVM version with CMake config files available, will pick one pretty much at random.
I experimented a bit and found that adding the below lines before `find_package` causes the **latest**, and not **random** version of LLVM to be used:
```
set(CMAKE_FIND_PACKAGE_SORT_ORDER NATURAL)
set(CMAKE_FIND_PACKAGE_SORT_DIRECTION DEC)
```
Relevant documentation is here:
* https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_SORT_ORDER.html
* https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_SORT_DIRECTION.html
I hope you find this change is useful and beneficial for the project.
> CMake: try to use latest LLVM version instead of randomly found version

- README.rst
- src/Output.cxx
- src/RunClang.cxx
Clang renamed `clang/AST/TypeNodes.{def => inc}` and replaced the
`createDriverOptTable` factory with a singleton returned by
`getDriverOptTable`.
> Port to LLVM/Clang SVN r375505 (trunk)

- src/Output.cxx
- test/expect/castxml1.any.FundamentalType-nullptr.xml.txt
Extend the `--castxml-output=1` format to recognize function call in
decltype. Create a dump node for the function return type.
> Output: Support function call inside decltype

- README.rst
> README: Document support for LLVM/Clang 10.0

- README.rst
- src/Detect.cxx
- src/Output.cxx
- src/Utils.cxx
The `llvm::StringRef` type now requires explicit conversion to `std::string`.  Such explicit conversions still work with older versions of LLVM/Clang too.
> Port to LLVM/Clang Git master as of 2020-02-13 (6c73246179)

- src/CMakeLists.txt
Clang 9 introduced a `clang-cpp` shared library that we can optionally
use instead of linking to the static libraries.
> cmake: Add option CLANG_LINK_CLANG_DYLIB to use clang-cpp shared lib

- src/RunClang.cxx
MSVC tools 14.23 and above declare `__builtin_assume_aligned` in
`intrin0.h` with a signature incompatible with Clang's builtin.  It is
guarded by `!defined(__clang__)` but that breaks when we simulate MSVC's
preprocessor.  Rename the builtin via preprocessing to avoid the
conflict.
> RunClang: Tolerate __builtin_assume_aligned declaration in MSVC header

- test/CMakeLists.txt
- test/input/assume_aligned.cxx
In #162 we left out a test case.  Add one now.
> test: Add case for __builtin_assume_aligned declaration in MSVC header

- README.rst
Was looking for a way to build this, hadn't yet looked at the `CastXML` organization, so I googled "kitware castxml download" and came across the superbuild.
> README: Add reference to CastXMLSuperbuild

- README.rst
- src/Output.cxx
- test/expect/castxml1.any.Field.xml.txt
- test/expect/gccxml.any.Field.xml.txt
- test/input/Field.cxx
Explicitly include Clang headers for SourceLocation and FileManager
instead of relying on other clang headers to provide them.
Fixes: #173
> Port to LLVM/Clang Git master as of 2020-07-13

- README.rst
> README: Document support for LLVM/Clang 11.0

- doc/manual/castxml.1.rst
- doc/manual/castxml.xsd
- test/CMakeLists.txt
- test/run.cmake
The schema is used for testing with xmllint and is linked from the documentation.
Note that for simplicity the schema isn't as precise as it could be.
* All callables (`Function`, `Method`, `Constructor`, `Converter`, etc) are described with only two types: `Function` and `Method` ( which extends `Function`).
* Attributes (like `__stdcall__` and `annotate()`) aren't explicitly enumerated. This is because CastXML encodes them in a space separated list, but `annotate()` attribute can contain spaces as well.
* Mixed IDs like `private:_10` in the `bases` attribute or `f1:5` in `location` are impossible to validate.
* XML Schema 1.1 can describe dependencies between XML attributes, but I'm sticking to Schema 1.0 for maximum compatibility.
Edit: tightened the type of various names. Some can be …
> doc,test: Add XML Schema definition for both output formats

- src/Detect.cxx
- src/Utils.cxx
- src/Utils.h
- test/expect/cmd.cc-msvc-bad-cmd.stderr.txt
- test/expect/cmd.cc-msvc-c-bad-cmd.stderr.txt
MSVC has no way to compile without producing the object file.
Previously we used `-FoNUL` to redirect the object file to the
null device, which `cl` opened internally as `NUL.obj`.
Windows 11 seems to treat `NUL.obj` as a real file, and only
plain `NUL` as the null device.  Opening `NUL.obj` in the
current working directory races with other CastXML processes.
Avoid this problem by putting the object file in a temporary
directory that is unique to the current process.
Fixes: #211
> Detect: Fix MSVC preprocessor settings detection on Windows 11

- README.rst
Also document a more recent version on the `main` branch that is known to work.
> README: Document support for LLVM/Clang 14.0

- src/Output.cxx
- test/expect/castxml1.any.using-declaration-ns.xml.txt
- test/expect/gccxml.any.using-declaration-ns.xml.txt
- test/input/using-declaration-ns.cxx
LLVM/Clang 14 introduced a `UsingType` indirection to represent type references through using declarations.  Report the underlying type as before.
See LLVM/Clang commit `e1600db19d63` ([AST] Add UsingType: a sugar type for types found via UsingDecl, 2021-11-19) and commit `af27466c5039` (Reland "[AST] Add UsingType: a sugar type for types found via UsingDecl", 2021-12-20).
Fixes: #220
> Output: Restore type references through using decls with LLVM/Clang 14+

- src/RunClang.cxx
- test/CMakeLists.txt
- test/cc-gnu.c
- test/expect/cmd.cc-gnu-intrinsics-arm64v8.stderr.txt
- test/input/intrinsics-arm64v8.cxx
LLVM/Clang predefines `__ARM_FEATURE_DIRECTED_ROUNDING` when ever it defines `__ARM_ARCH >= 8`.  Its corresponding `arm_neon.h` intrinsics header relies on the feature macro to provide rounding intrinsics. GCC does not define the feature macro, but its own `arm_neon.h` provides the rounding intrinsics whenever `__ARM_ARCH >= 8`.
Teach CastXML to add the `__ARM_FEATURE_DIRECTED_ROUNDING` definition whenever the compiler's predefined macros include `__ARM_ARCH >= 8` so that the `arm_neon.h` intrinsics header we distribute will provide the rounding intrinsics.
Fixes: #223
> RunClang: Fix arm64v8 rounding intrinsics when simulating GCC

- test/expect/cmd.cc-msvc-c-src-c-cmd.stderr.txt
- test/expect/cmd.cc-msvc-src-cxx-cmd.stderr.txt
The LLVM/Clang package against which CastXML is built may be configured to add `-internal-isystem /usr/local/include` or similar flags.  Update the expected output from `cmd.cc-msvc.*cmd` tests to tolerate them after the intended `-isystem` flags.
Fixes: #234
> test: Tolerate '-internal-*' flags after '-isystem' flags

- README.rst
No one has posted to the list since 2018, so it has been retired.
> README: Remove link to now-retired CastXML mailing list

- src/RunClang.cxx
Since commit 825cca7df68c0282339e3d0ec64e75f40fd57ed9 (RunClang: Delay class implicit members until end of parsing, 2014-12-08, v0.2.0~211) we `enableIncrementalProcessing()` to defer parser tear down.
Since LLVM/Clang commit `247fa04116a6` ([clang] Add a new annotation token: annot_repl_input_end, 2023-05-16), incremental processing causes preprocessing to get stuck at the end of a file because it never gets an `eof` token.  See `clang/lib/Frontend/PrintPreprocessedOutput.cpp` in `DoPrintPreprocessedInput` and `DoPrintMacros`.
Fortunately we do not need incremental processing in preprocessing modes.
> Port to LLVM/Clang Git release/17.x as of 2023-08-15 (2f0fb9346d0)

- README.rst
- src/Output.cxx
The return types of `getKeyword` and `getTagKind` are now defined using `enum class` types.
Also use `clang::FileEntryRef` with LLVM/Clang >= 12 to avoid a deprecation coming in LLVM/Clang 18.
> Port to LLVM/Clang Git main as of 2024-01-03

- src/Output.cxx
`isPure` was renamed to `isPureVirtual`.
> Port to LLVM/Clang Git release/18.x as of 2024-02-05 (900e7cbfdee)

- README.rst
> README: Document support for LLVM/Clang 18.1

- CMakeLists.txt
Since LLVM/Clang change [D157028](https://reviews.llvm.org/D157028), preprocessing the clang driver headers requires standard-conforming preprocessor behavior.  Add the MSVC `-Zc:preprocessor` flag for this, as LLVM/Clang change [D135128](https://reviews.llvm.org/D135128) did.
Fixes: #256
> Fix compilation against LLVM/Clang 18.x with MSVC

- src/RunClang.cxx
- test/cc-gnu.c
GCC 13 added support for C++23 fixed-size floating-point types and literal suffixes.  They are used in libstdc++ when compiled as C++23. Clang does not yet implement the types as of LLVM/Clang 18.  Remove the corresponding builtin definitions when simulating a GNU compiler.
> RunClang: Remove GCC builtin definitions for features Clang does not implement

- src/RunClang.cxx
- test/CMakeLists.txt
- test/expect/castxml1.any.GNU-attr-assume.xml.txt
- test/expect/castxml1.c.GNU-attr-assume.xml.txt
- test/expect/cmd.cc-gnu-c-src-c-E.stdout.txt
- test/expect/cmd.cc-gnu-c-tgt-i386-opt-E.stdout.txt
- test/expect/cmd.cc-gnu-src-cxx-E.stdout.txt
- test/expect/cmd.cc-gnu-tgt-i386-opt-E.stdout.txt
- test/expect/gccxml.any.GNU-attr-assume.xml.txt
- test/expect/gccxml.c.GNU-attr-assume.xml.txt
- test/input/GNU-attr-assume.c
- test/input/GNU-attr-assume.cxx
GCC 13 added support for an `__assume__(...)` statement attribute. GCC 14's libstdc++ uses it.  As of LLVM/Clang 18, it is not yet supported.  Work around the problem by mapping the attribute to an empty string.
Fixes: #259
> RunClang: Tolerate GNU __attribute__((__assume__(...)))

- test/expect/cmd.cc-gnu-c-tgt-i386-opt-E.stdout.txt
- test/expect/cmd.cc-gnu-tgt-i386-opt-E.stdout.txt
Since #264 both `__float80` and `__float128` may individually be defined or not defined.  Fix the expected order when they are both defined.
> test: Fix expected cc-gnu predefined macro ordering

- README.rst
- test/expect/cmd.castxml-empty-c++98-c.stderr.txt
- test/expect/cmd.gccxml-empty-c++98-c.stderr.txt
> README: Document support for LLVM/Clang 19.1

- test/expect/cmd.predefined-macros.stdout.txt.in
It happens to be sorted among our version macros, so tolerate it if it appears.
> test: Tolerate predefined __cdecl macro from LLVM/Clang

- test/expect/cmd.predefined-macros.stdout.txt.in
The output for the predefined macros test changed for clang 20 on ppc64le causing two test to start failing:
The following tests FAILED:
50 - cmd.gccxml-predefined-macros (Failed)
51 - cmd.castxml-predefined-macros (Failed)
The reason for the failure is that two new macros appear in the alphabetical list between the __castxml* and __clang* macros causing the expected test output to no longer match:
#define __castxml_patch__ 11
#define __cbcdtd __builtin_ppc_cbcdtd
#define __cdtbcd __builtin_ppc_cdtbcd
#define __clang__ 1
> test: Tolerate more predefined '__c*' macros from LLVM/Clang

- README.rst
- src/Output.cxx
`MemberPointerType` has a new way to get the containing class.
> Port to LLVM/Clang Git main as of 2025-04-08

- src/RunClang.cxx
- test/expect/castxml1.any.Class-template-constructor-template.xml.txt
- test/expect/gccxml.any.Class-template-constructor-template.xml.txt
`DiagnosticOptions` is no longer intrusively reference counted.
LLVM/Clang commit `8c5a307bd8d4` ([Clang] Bypass TAD during overload resolution if a perfect match exists, 2025-04-18) reduced duplication of reference-to-class-template-specialization types, so update our test case from commit fc66c82e1de6afd4453b7223c51de50428a40769 (test: Show duplication of reference-to-class-template-specialization types, 2014-03-27, `v0.2.0~258`).
>  Port to LLVM/Clang Git main as of 2025-06-12
